/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package employee.recognition.service.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import employee.recognition.service.model.Appreciation;
import employee.recognition.service.model.AppreciationModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Appreciation service. Represents a row in the &quot;ER_Appreciation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AppreciationModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AppreciationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppreciationImpl
 * @generated
 */
public class AppreciationModelImpl
	extends BaseModelImpl<Appreciation> implements AppreciationModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a appreciation model instance should use the <code>Appreciation</code> interface instead.
	 */
	public static final String TABLE_NAME = "ER_Appreciation";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"appreciationId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"fromUserId", Types.BIGINT}, {"toUserId", Types.BIGINT},
		{"message", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("appreciationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("fromUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("toUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("message", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ER_Appreciation (uuid_ VARCHAR(75) null,appreciationId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,fromUserId LONG,toUserId LONG,message VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ER_Appreciation";

	public static final String ORDER_BY_JPQL =
		" ORDER BY appreciation.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ER_Appreciation.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TOUSERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CREATEDATE_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AppreciationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _appreciationId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAppreciationId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _appreciationId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Appreciation.class;
	}

	@Override
	public String getModelClassName() {
		return Appreciation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Appreciation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Appreciation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appreciation, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((Appreciation)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Appreciation, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Appreciation, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Appreciation)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Appreciation, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Appreciation, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Appreciation, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Appreciation, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Appreciation, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Appreciation, Object>>();
		Map<String, BiConsumer<Appreciation, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Appreciation, ?>>();

		attributeGetterFunctions.put("uuid", Appreciation::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Appreciation, String>)Appreciation::setUuid);
		attributeGetterFunctions.put(
			"appreciationId", Appreciation::getAppreciationId);
		attributeSetterBiConsumers.put(
			"appreciationId",
			(BiConsumer<Appreciation, Long>)Appreciation::setAppreciationId);
		attributeGetterFunctions.put("groupId", Appreciation::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<Appreciation, Long>)Appreciation::setGroupId);
		attributeGetterFunctions.put("companyId", Appreciation::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<Appreciation, Long>)Appreciation::setCompanyId);
		attributeGetterFunctions.put("userId", Appreciation::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Appreciation, Long>)Appreciation::setUserId);
		attributeGetterFunctions.put("userName", Appreciation::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<Appreciation, String>)Appreciation::setUserName);
		attributeGetterFunctions.put("createDate", Appreciation::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<Appreciation, Date>)Appreciation::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", Appreciation::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<Appreciation, Date>)Appreciation::setModifiedDate);
		attributeGetterFunctions.put("fromUserId", Appreciation::getFromUserId);
		attributeSetterBiConsumers.put(
			"fromUserId",
			(BiConsumer<Appreciation, Long>)Appreciation::setFromUserId);
		attributeGetterFunctions.put("toUserId", Appreciation::getToUserId);
		attributeSetterBiConsumers.put(
			"toUserId",
			(BiConsumer<Appreciation, Long>)Appreciation::setToUserId);
		attributeGetterFunctions.put("message", Appreciation::getMessage);
		attributeSetterBiConsumers.put(
			"message",
			(BiConsumer<Appreciation, String>)Appreciation::setMessage);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getAppreciationId() {
		return _appreciationId;
	}

	@Override
	public void setAppreciationId(long appreciationId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_appreciationId = appreciationId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public long getFromUserId() {
		return _fromUserId;
	}

	@Override
	public void setFromUserId(long fromUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fromUserId = fromUserId;
	}

	@Override
	public String getFromUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getFromUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setFromUserUuid(String fromUserUuid) {
	}

	@Override
	public long getToUserId() {
		return _toUserId;
	}

	@Override
	public void setToUserId(long toUserId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_toUserId = toUserId;
	}

	@Override
	public String getToUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getToUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setToUserUuid(String toUserUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalToUserId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("toUserId"));
	}

	@Override
	public String getMessage() {
		if (_message == null) {
			return "";
		}
		else {
			return _message;
		}
	}

	@Override
	public void setMessage(String message) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_message = message;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Appreciation.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Appreciation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Appreciation toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Appreciation>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AppreciationImpl appreciationImpl = new AppreciationImpl();

		appreciationImpl.setUuid(getUuid());
		appreciationImpl.setAppreciationId(getAppreciationId());
		appreciationImpl.setGroupId(getGroupId());
		appreciationImpl.setCompanyId(getCompanyId());
		appreciationImpl.setUserId(getUserId());
		appreciationImpl.setUserName(getUserName());
		appreciationImpl.setCreateDate(getCreateDate());
		appreciationImpl.setModifiedDate(getModifiedDate());
		appreciationImpl.setFromUserId(getFromUserId());
		appreciationImpl.setToUserId(getToUserId());
		appreciationImpl.setMessage(getMessage());

		appreciationImpl.resetOriginalValues();

		return appreciationImpl;
	}

	@Override
	public Appreciation cloneWithOriginalValues() {
		AppreciationImpl appreciationImpl = new AppreciationImpl();

		appreciationImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		appreciationImpl.setAppreciationId(
			this.<Long>getColumnOriginalValue("appreciationId"));
		appreciationImpl.setGroupId(
			this.<Long>getColumnOriginalValue("groupId"));
		appreciationImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		appreciationImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		appreciationImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		appreciationImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		appreciationImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		appreciationImpl.setFromUserId(
			this.<Long>getColumnOriginalValue("fromUserId"));
		appreciationImpl.setToUserId(
			this.<Long>getColumnOriginalValue("toUserId"));
		appreciationImpl.setMessage(
			this.<String>getColumnOriginalValue("message"));

		return appreciationImpl;
	}

	@Override
	public int compareTo(Appreciation appreciation) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), appreciation.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Appreciation)) {
			return false;
		}

		Appreciation appreciation = (Appreciation)object;

		long primaryKey = appreciation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Appreciation> toCacheModel() {
		AppreciationCacheModel appreciationCacheModel =
			new AppreciationCacheModel();

		appreciationCacheModel.uuid = getUuid();

		String uuid = appreciationCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			appreciationCacheModel.uuid = null;
		}

		appreciationCacheModel.appreciationId = getAppreciationId();

		appreciationCacheModel.groupId = getGroupId();

		appreciationCacheModel.companyId = getCompanyId();

		appreciationCacheModel.userId = getUserId();

		appreciationCacheModel.userName = getUserName();

		String userName = appreciationCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			appreciationCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			appreciationCacheModel.createDate = createDate.getTime();
		}
		else {
			appreciationCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			appreciationCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			appreciationCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		appreciationCacheModel.fromUserId = getFromUserId();

		appreciationCacheModel.toUserId = getToUserId();

		appreciationCacheModel.message = getMessage();

		String message = appreciationCacheModel.message;

		if ((message != null) && (message.length() == 0)) {
			appreciationCacheModel.message = null;
		}

		return appreciationCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Appreciation, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Appreciation, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Appreciation, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Appreciation)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Appreciation>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Appreciation.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _appreciationId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private long _fromUserId;
	private long _toUserId;
	private String _message;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Appreciation, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Appreciation)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("appreciationId", _appreciationId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("fromUserId", _fromUserId);
		_columnOriginalValues.put("toUserId", _toUserId);
		_columnOriginalValues.put("message", _message);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("appreciationId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("fromUserId", 256L);

		columnBitmasks.put("toUserId", 512L);

		columnBitmasks.put("message", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Appreciation _escapedModel;

}