/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package employee.recognition.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Appreciation service. Represents a row in the &quot;ER_Appreciation&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>employee.recognition.service.model.impl.AppreciationModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>employee.recognition.service.model.impl.AppreciationImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Appreciation
 * @generated
 */
@ProviderType
public interface AppreciationModel
	extends BaseModel<Appreciation>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a appreciation model instance should use the {@link Appreciation} interface instead.
	 */

	/**
	 * Returns the primary key of this appreciation.
	 *
	 * @return the primary key of this appreciation
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this appreciation.
	 *
	 * @param primaryKey the primary key of this appreciation
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this appreciation.
	 *
	 * @return the uuid of this appreciation
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this appreciation.
	 *
	 * @param uuid the uuid of this appreciation
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the appreciation ID of this appreciation.
	 *
	 * @return the appreciation ID of this appreciation
	 */
	public long getAppreciationId();

	/**
	 * Sets the appreciation ID of this appreciation.
	 *
	 * @param appreciationId the appreciation ID of this appreciation
	 */
	public void setAppreciationId(long appreciationId);

	/**
	 * Returns the group ID of this appreciation.
	 *
	 * @return the group ID of this appreciation
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this appreciation.
	 *
	 * @param groupId the group ID of this appreciation
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this appreciation.
	 *
	 * @return the company ID of this appreciation
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this appreciation.
	 *
	 * @param companyId the company ID of this appreciation
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this appreciation.
	 *
	 * @return the user ID of this appreciation
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this appreciation.
	 *
	 * @param userId the user ID of this appreciation
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this appreciation.
	 *
	 * @return the user uuid of this appreciation
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this appreciation.
	 *
	 * @param userUuid the user uuid of this appreciation
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this appreciation.
	 *
	 * @return the user name of this appreciation
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this appreciation.
	 *
	 * @param userName the user name of this appreciation
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this appreciation.
	 *
	 * @return the create date of this appreciation
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this appreciation.
	 *
	 * @param createDate the create date of this appreciation
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this appreciation.
	 *
	 * @return the modified date of this appreciation
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this appreciation.
	 *
	 * @param modifiedDate the modified date of this appreciation
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the from user ID of this appreciation.
	 *
	 * @return the from user ID of this appreciation
	 */
	public long getFromUserId();

	/**
	 * Sets the from user ID of this appreciation.
	 *
	 * @param fromUserId the from user ID of this appreciation
	 */
	public void setFromUserId(long fromUserId);

	/**
	 * Returns the from user uuid of this appreciation.
	 *
	 * @return the from user uuid of this appreciation
	 */
	public String getFromUserUuid();

	/**
	 * Sets the from user uuid of this appreciation.
	 *
	 * @param fromUserUuid the from user uuid of this appreciation
	 */
	public void setFromUserUuid(String fromUserUuid);

	/**
	 * Returns the to user ID of this appreciation.
	 *
	 * @return the to user ID of this appreciation
	 */
	public long getToUserId();

	/**
	 * Sets the to user ID of this appreciation.
	 *
	 * @param toUserId the to user ID of this appreciation
	 */
	public void setToUserId(long toUserId);

	/**
	 * Returns the to user uuid of this appreciation.
	 *
	 * @return the to user uuid of this appreciation
	 */
	public String getToUserUuid();

	/**
	 * Sets the to user uuid of this appreciation.
	 *
	 * @param toUserUuid the to user uuid of this appreciation
	 */
	public void setToUserUuid(String toUserUuid);

	/**
	 * Returns the message of this appreciation.
	 *
	 * @return the message of this appreciation
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this appreciation.
	 *
	 * @param message the message of this appreciation
	 */
	public void setMessage(String message);

	@Override
	public Appreciation cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}